server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #http://registry-service.default.svc.cluster.local/eureka/
  healthcheck:
    enabled: true

spring:
  application:
    name: gateway
ribbon:
  ReadTimeout: 60000
